const constants={
   ENV:{
    DEBUG:true,
   },
    DISPLAY:{
        RESOLUTION:{
            FULL_HD:{
                WIDTH:1920,
                HEIGHT:1080,
            }
        }
    },
    AUDIO:{
        BACKGROUND_AUDIO:"bgAudio",
        ENEMY_GROUP_ENTRY:"groupEntry",
        BULLET_FIRE:"bulletFire"
    },
    GAME_LOGIC:{
        PHYSICS:{
            COLLISION:{
                CATEGORY_ENEMY:0b0001,
                CATEGORY_PLAYER:0b0010,
                CATEGORY_LASER:0b0100,
            }
        },
        PROJECTILE:{
            SPEED:-9,
            MAX_COUNT:15,
            MIN_TIME_GAP:150
        },
        ENEMY:{
            PER_LEVEL_TIME_GAP:[2.7,2.3,2.0,1.5,1],
            PER_LEVEL_COUNT:[2,3,4,5,5],
            HEALTH_MUL_FACTOR:1.2,
        },
        DEPTHS:{
            BACKGROUND:100,
            GAME_OBJECTS:200,
            UI:300,
        },
    },
    SCENES:{
        LOADING_SCENE:"loading",
        ARENA_SCENE:"arena"
    },
    ANIMATIONS:{
        FRAME_RATE:8,
        ENEMIES:{
            MINE:"MINE",
            SPACESHIP_1:"SPACESHIP_1",
            SPACESHIP_2:"SPACESHIP_2",
            SPACESHIP_3:"SPACESHIP_3",
            SPACESHIP_4:"SPACESHIP_4",
            SPACESHIP_5:"SPACESHIP_5",
        }
    },
    EVENTS:{
        ON_ADD:"_on_add"
    },
    GAME_OBJECTS:{
        NAMES:{
            PLAYER:"player",
            BULLET:"bullet",
            ENEMY:"enemy"
        },
        BACKGROUNDS:{
            DEFAULT:"background"
        },
        LOGO:"companyLogo",
        PLAYER:{
            SHIPS:{
                DEFAULT:"player"
            }
        },
        LAYERS:{
            GAME_OBJECTS:"gameObjects",
            UI:"ui"
        },
        PROJECTILE:{
            LASER:"laser"
        },
        ENEMIES:{
            MINE:"mine-1",
            SPACESHIP_1:"spaceship1-1",
            SPACESHIP_2:"spaceship2-1",
            SPACESHIP_3:"spaceship3-1",
            SPACESHIP_4:"spaceship4-1",
            SPACESHIP_5:"spaceship5-1",
        
          
        }
        
    }
};

export default constants;